"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { MessageSquareText, TriangleAlert } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { ApiErrorPanel } from "@/components/shared-states/api-error-panel";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useNarrate } from "@/lib/api/hooks/use-decisions";
import { queryKeys } from "@/lib/api/query-keys";
import type { AcceptedNarrationResult } from "../workflow-results";

export function NarrationStage({ stateId, sourceSignature, retained, current, onAccepted }: { stateId: string; sourceSignature: string; retained?: AcceptedNarrationResult; current?: AcceptedNarrationResult; onAccepted: (value: AcceptedNarrationResult) => void }) {
  const client = useQueryClient(); const mutation = useNarrate(); const [error, setError] = useState<unknown>(); const generation = useRef(0); const controller = useRef<AbortController | undefined>(undefined); const sourceRef = useRef(sourceSignature);
  useEffect(() => { if (sourceRef.current !== sourceSignature) { controller.current?.abort(); generation.current += 1; sourceRef.current = sourceSignature; } }, [sourceSignature]);
  useEffect(() => () => { controller.current?.abort(); generation.current += 1; }, []);
  async function submit() { if (mutation.isPending) return; const request = ++generation.current; const captured = sourceSignature; const abort = new AbortController(); controller.current = abort; setError(undefined); try { const response = await mutation.mutateAsync({ stateId, signal: abort.signal }); if (request !== generation.current || sourceRef.current !== captured) return; client.setQueryData(queryKeys.narration(stateId), response); onAccepted({ response, sourceSignature: captured }); } catch (cause) { if (!abort.signal.aborted && request === generation.current) setError(cause); } finally { if (controller.current === abort) controller.current = undefined; } }
  const shown = current ?? retained;
  return <div className="grid gap-5 xl:grid-cols-[minmax(18rem,.65fr)_minmax(0,1.35fr)]"><Card><CardHeader><CardTitle>Recommendation explanation</CardTitle><CardDescription>Request the backend narration explicitly. The browser displays it exactly and adds no treatment or diagnostic guidance.</CardDescription></CardHeader><CardContent className="grid gap-4"><Button type="button" onClick={() => void submit()} disabled={mutation.isPending} aria-busy={mutation.isPending}><MessageSquareText className="size-4" />{mutation.isPending ? "Requesting explanation…" : "Request explanation"}</Button>{error ? <ApiErrorPanel error={error} title="Explanation unavailable" /> : null}</CardContent></Card><div>{shown && !current ? <Alert variant="warning" className="mb-4"><TriangleAlert className="size-5" /><AlertTitle>Previous explanation superseded</AlertTitle><AlertDescription>The recommendation changed. Request a new explanation.</AlertDescription></Alert> : null}{shown ? <div className="grid gap-4"><Card><CardHeader><CardDescription>Explains the deterministic recommendation</CardDescription><CardTitle>{shown.response.headline}</CardTitle></CardHeader><CardContent className="grid gap-3"><p className="leading-7">{shown.response.rationale}</p>{shown.response.caution ? <Alert variant="warning"><TriangleAlert className="size-5" /><AlertTitle>Caution</AlertTitle><AlertDescription>{shown.response.caution}</AlertDescription></Alert> : null}</CardContent></Card>{current ? <Card><CardHeader><CardTitle>Workflow complete</CardTitle><CardDescription>All nine state-scoped workflow stages are current.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-4 text-sm font-semibold text-[var(--agronomy-strong)]"><Link href={`/history/${encodeURIComponent(stateId)}`} className="underline">History</Link><Link href={`/actions/${encodeURIComponent(stateId)}`} className="underline">Record actual action</Link><Link href={`/cycle/${encodeURIComponent(stateId)}`} className="underline">Active cycle</Link><Link href="/farms" className="underline">Farms and plots</Link></CardContent></Card> : null}</div> : <Alert variant="neutral"><MessageSquareText className="size-5" /><AlertTitle>No explanation yet</AlertTitle><AlertDescription>Request it explicitly after the current recommendation.</AlertDescription></Alert>}</div></div>;
}
