"use client";
import { useEffect, useRef, useState } from "react";
import { Layers3, LockKeyhole } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { ApiErrorPanel } from "@/components/shared-states/api-error-panel";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useUpdateTwinState, type CachedDiseaseEvidence } from "@/lib/api/hooks/use-workflow";
import { queryKeys } from "@/lib/api/query-keys";
import type { WorkflowIdentityStore } from "../identity-store";
import type { AcceptedAdvancementResult, AcceptedTwinResult, AcceptedWaterResult } from "../workflow-results";
import { AdvancementPanel } from "../advancement/advancement-panel";
import { twinSourceSignature } from "./twin-utils";
import { TwinResult } from "./twin-result";

export function TwinStage({ stateId, disease, water, current, identityStore, workflowSourceSignature, mutationLocked, onPending, onAccepted, onAdvanced }: { stateId: string; disease: CachedDiseaseEvidence; water: AcceptedWaterResult; current?: AcceptedTwinResult; identityStore: WorkflowIdentityStore; workflowSourceSignature: string; mutationLocked: boolean; onPending: (pending: boolean) => void; onAccepted: (value: AcceptedTwinResult) => void; onAdvanced: (value: { water: AcceptedWaterResult; twin?: AcceptedTwinResult; advancement: AcceptedAdvancementResult }) => void }) {
  const queryClient = useQueryClient(); const mutation = useUpdateTwinState(); const [error, setError] = useState<unknown>(); const [tab, setTab] = useState<"twin" | "advance">("twin");
  const source = twinSourceSignature(stateId, disease.response, water.response); const sourceRef = useRef(source); const generation = useRef(0); const mounted = useRef(true);
  useEffect(() => { sourceRef.current = source; }, [source]);
  useEffect(() => () => { mounted.current = false; generation.current += 1; }, []);
  async function update() { if (mutation.isPending || mutationLocked) return; const request = ++generation.current; const captured = source; const controller = new AbortController(); setError(undefined); onPending(true); try { const response = await mutation.mutateAsync({ stateId, signal: controller.signal }); if (!mounted.current || generation.current !== request || sourceRef.current !== captured) return; const accepted = { response, sourceSignature: captured } satisfies AcceptedTwinResult; queryClient.setQueryData(queryKeys.twinState(stateId), response); onAccepted(accepted); void queryClient.invalidateQueries({ queryKey: queryKeys.session(stateId), exact: true }); } catch (cause) { if (mounted.current && generation.current === request) setError(cause); } finally { if (generation.current === request) onPending(false); } }
  const currentTwin = current?.sourceSignature === source ? current : undefined;
  return <div className="grid gap-5"><div role="tablist" aria-label="Canonical state operations" className="flex w-fit gap-2 rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-raised)] p-1"><Button type="button" variant={tab === "twin" ? "default" : "ghost"} role="tab" aria-selected={tab === "twin"} onClick={() => setTab("twin")}>Canonical twin</Button><Button type="button" variant={tab === "advance" ? "default" : "ghost"} role="tab" aria-selected={tab === "advance"} onClick={() => setTab("advance")} disabled={!currentTwin}>Advance one day</Button></div>{tab === "twin" ? <div className="grid gap-5 xl:grid-cols-[minmax(18rem,.7fr)_minmax(0,1.3fr)]"><Card><CardHeader><CardTitle>Assemble canonical twin</CardTitle><CardDescription>FastAPI combines current supporting disease evidence with current deterministic water lineage.</CardDescription></CardHeader><CardContent className="grid gap-4"><dl className="grid gap-3 text-sm"><Row term="Disease evidence" value={`${disease.response.predicted_label} · supporting AI`} /><Row term="Water observation" value={`${water.response.water_observation_id} · sequence ${water.response.water_sequence}`} /></dl><Button type="button" onClick={() => void update()} disabled={mutation.isPending || mutationLocked} aria-busy={mutation.isPending}><Layers3 className="size-4" aria-hidden="true" />{mutation.isPending ? "Updating canonical twin…" : currentTwin ? "Update canonical twin again" : "Update canonical twin"}</Button>{error ? <ApiErrorPanel error={error} title="Canonical twin update unavailable" /> : null}</CardContent></Card><div className="min-w-0">{currentTwin ? <TwinResult result={currentTwin.response} /> : <Alert variant="neutral"><Layers3 className="size-5" aria-hidden="true" /><AlertTitle>No current canonical twin result</AlertTitle><AlertDescription>Run the explicit update. A loaded session snapshot does not fabricate lineage or snapshot metadata.</AlertDescription></Alert>}</div></div> : currentTwin ? <AdvancementPanel stateId={stateId} disease={disease} water={water} twin={currentTwin} workflowSourceSignature={workflowSourceSignature} identityStore={identityStore} mutationLocked={mutationLocked} onPending={onPending} onApplied={onAdvanced} /> : <Alert variant="neutral"><LockKeyhole className="size-5" aria-hidden="true" /><AlertTitle>One-day advancement blocked</AlertTitle><AlertDescription>Create a current canonical twin first.</AlertDescription></Alert>}</div>;
}
function Row({ term, value }: { term: string; value: string }) { return <div><dt className="text-[var(--text-muted)]">{term}</dt><dd className="break-all font-semibold">{value}</dd></div>; }
