import { useEffect, useRef, useState } from 'react';
import { Text } from 'react-native';
import { ErrorState, MetricRow, PrimaryButton, SectionCard, StatusBadge, TechnicalDetails } from '@/components/ui';
import { CropTwinApiError, toUserFacingError, type UpdateTwinStateResponse } from '@/lib/api';
import { useTwinState, useUpdateTwinState } from './hooks';

export function TwinWorkflow({ stateId, current }: { stateId: string; current?: UpdateTwinStateResponse }) {
  const mutation = useUpdateTwinState(stateId); const cached = useTwinState(stateId).data; const result = current ?? cached; const [error, setError] = useState<unknown>(); const controller = useRef<AbortController | undefined>(undefined); useEffect(() => () => controller.current?.abort(), []);
  async function submit() { if (mutation.isPending) return; controller.current = new AbortController(); setError(undefined); try { await mutation.mutateAsync({ signal: controller.current.signal }); } catch (cause) { if (!(cause instanceof CropTwinApiError && cause.kind === 'cancelled')) setError(cause); } }
  const friendly = error ? toUserFacingError(error) : undefined; const missing = error instanceof CropTwinApiError && Array.isArray(error.details.missing) ? error.details.missing : []; const missingDisease = missing.includes('latest_disease_state');
  return <SectionCard title="Canonical twin update" accent="agronomy"><Text>FastAPI builds the canonical twin from its persisted disease, growth, and water observations. Local disease cache absence does not block this request.</Text><PrimaryButton disabled={mutation.isPending} onPress={() => void submit()}>{mutation.isPending ? 'Updating canonical twin…' : 'Update canonical twin'}</PrimaryButton>{friendly ? <ErrorState title="Canonical twin unavailable" description={missingDisease ? 'FastAPI reports incomplete evidence. Add disease evidence, then explicitly retry this update.' : friendly.description} technicalDetails={friendly.technicalDetails} /> : null}{result ? <TwinResult result={result} /> : null}</SectionCard>;
}

export function TwinResult({ result }: { result: UpdateTwinStateResponse }) { const state = result.current_state; return <SectionCard title={result.snapshot_created ? 'New canonical twin snapshot created' : 'Canonical twin already matched'} accent="agronomy"><StatusBadge label={result.snapshot_created ? 'Snapshot created' : 'Snapshot reused'} tone="success" /><MetricRow label="Growth stage" value={state.growth_stage.replaceAll('_', ' ')} /><MetricRow label="Moisture state" value={state.estimated_moisture_state.replaceAll('_', ' ')} /><MetricRow label="Stress band" value={state.stress_band} /><MetricRow label="State history count" value={result.state_history_count} /><TechnicalDetails details={{ state_id: result.state_id, snapshot_id: result.snapshot_id, snapshot_created: result.snapshot_created, observed_at: state.observed_at, computed_at: state.computed_at, last_update_time: state.last_update_time }} /></SectionCard>; }
