"use client";

import { Calculator, CheckCircle2, RotateCcw } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, Input, Select } from "@/components/ui/form-controls";
import { acceptIrrigationDraft, currentIrrigationSignature, type AcceptedIrrigation, type IrrigationDraft, type IrrigationMode } from "./irrigation-draft";

export function IrrigationStage({ stateId, draft, accepted, purpose = "water", onDraftChange, onAccept }: { stateId: string; draft: IrrigationDraft; accepted?: AcceptedIrrigation; purpose?: "water" | "advancement"; onDraftChange: (draft: IrrigationDraft) => void; onAccept: (accepted: AcceptedIrrigation) => void }) {
  let prepared: AcceptedIrrigation | undefined;
  let error: string | undefined;
  try { prepared = acceptIrrigationDraft(stateId, draft); } catch (cause) { error = cause instanceof Error ? cause.message : "Irrigation input is invalid."; }
  const stale = Boolean(accepted && accepted.semanticSignature !== currentIrrigationSignature(stateId, draft));
  const update = (values: Partial<IrrigationDraft>) => onDraftChange({ ...draft, ...values });

  return <div className="grid gap-5 xl:grid-cols-[minmax(0,1.15fr)_minmax(20rem,0.85fr)]">
    <Card><CardHeader><CardTitle>Prepare recent irrigation</CardTitle><CardDescription>Choose one transparent input method. A stable event ID is materialized only for an explicit {purpose === "advancement" ? "advancement" : "water"} request.</CardDescription></CardHeader><CardContent className="grid gap-5">
      <Field label="Input mode" htmlFor="irrigation-mode"><Select id="irrigation-mode" value={draft.mode} onChange={(event) => update({ mode: event.target.value as IrrigationMode })}><option value="none">No recent irrigation</option><option value="direct">Known irrigation depth in millimetres</option><option value="litres_area">Total litres plus irrigated area</option><option value="drip_runtime">Drip runtime and emitter details</option></Select></Field>
      {draft.mode !== "none" ? <Field label="Event date and time (local)" htmlFor="irrigation-timestamp"><Input id="irrigation-timestamp" type="datetime-local" value={draft.timestamp} onChange={(event) => update({ timestamp: event.target.value })} /></Field> : <Alert variant="neutral"><Calculator className="size-5" aria-hidden="true" /><AlertTitle>No recent irrigation selected</AlertTitle><AlertDescription>This is a deliberate input choice and remains distinct from incomplete data.</AlertDescription></Alert>}
      {draft.mode === "direct" ? <Field label="Irrigation depth (mm)" htmlFor="irrigation-depth"><Input id="irrigation-depth" type="number" min="0" step="any" value={draft.directDepth} onChange={(event) => update({ directDepth: event.target.value })} /></Field> : null}
      {draft.mode === "litres_area" ? <div className="grid gap-4 sm:grid-cols-2"><Field label="Total water applied (litres)" htmlFor="irrigation-litres"><Input id="irrigation-litres" type="number" min="0" step="any" value={draft.totalLitres} onChange={(event) => update({ totalLitres: event.target.value })} /></Field><Field label="Irrigated area (m²)" htmlFor="irrigation-litres-area"><Input id="irrigation-litres-area" type="number" min="0" step="any" value={draft.litresArea} onChange={(event) => update({ litresArea: event.target.value })} /></Field></div> : null}
      {draft.mode === "drip_runtime" ? <div className="grid gap-4 sm:grid-cols-2"><Field label="Emitter count" htmlFor="irrigation-emitters"><Input id="irrigation-emitters" type="number" min="1" step="1" value={draft.emitterCount} onChange={(event) => update({ emitterCount: event.target.value })} /></Field><Field label="Emitter flow (litres/hour)" htmlFor="irrigation-flow"><Input id="irrigation-flow" type="number" min="0" step="any" value={draft.emitterFlow} onChange={(event) => update({ emitterFlow: event.target.value })} /></Field><Field label="Runtime (minutes)" htmlFor="irrigation-runtime"><Input id="irrigation-runtime" type="number" min="0" step="any" value={draft.runtimeMinutes} onChange={(event) => update({ runtimeMinutes: event.target.value })} /></Field><Field label="Irrigated area (m²)" htmlFor="irrigation-drip-area"><Input id="irrigation-drip-area" type="number" min="0" step="any" value={draft.dripArea} onChange={(event) => update({ dripArea: event.target.value })} /></Field></div> : null}
      {error ? <p role="alert" className="text-sm font-semibold text-[var(--state-destructive-strong)]">{error}</p> : null}
      {stale ? <Alert variant="warning"><RotateCcw className="size-5" aria-hidden="true" /><AlertTitle>Accepted irrigation input is stale</AlertTitle><AlertDescription>An input changed. Accept the current preparation again.</AlertDescription></Alert> : null}
      <Button type="button" className="w-fit" disabled={!prepared} onClick={() => prepared && onAccept(prepared)}>Accept irrigation input</Button><p className="text-xs text-[var(--text-muted)]">Prepared for {purpose === "advancement" ? "one-day advancement" : "water-state computation"}. Not submitted to the agronomy engine yet.</p>
    </CardContent></Card>
    <Card><CardHeader><CardTitle>Transparent conversion</CardTitle><CardDescription>Display values may be rounded; the accepted draft retains full finite precision.</CardDescription></CardHeader><CardContent>{prepared ? <div className="grid gap-4"><dl className="grid gap-3 text-sm"><Row term="Source" value={prepared.source ?? "No event"} /><Row term="Status" value={prepared.distinction.replaceAll("_", " ")} />{prepared.timestamp ? <Row term="Aware timestamp" value={prepared.timestamp} /> : null}{prepared.amountMm !== null ? <Row term="Calculated depth" value={`${prepared.amountMm.toFixed(6)} mm (display formatting)`} /> : null}{"total_litres" in prepared.inputDetails ? <Row term="Calculated total litres" value={`${prepared.inputDetails.total_litres} L`} /> : null}</dl>{draft.mode === "litres_area" ? <code className="rounded-lg bg-[var(--surface-sunken)] p-3 text-xs">amount_mm = total_litres / irrigated_area_m2</code> : null}{draft.mode === "drip_runtime" ? <code className="rounded-lg bg-[var(--surface-sunken)] p-3 text-xs">runtime_hours = runtime_minutes / 60{"\n"}total_litres = emitters × flow × runtime_hours{"\n"}amount_mm = total_litres / area_m2</code> : null}{accepted && !stale ? <Alert variant="success"><CheckCircle2 className="size-5" aria-hidden="true" /><AlertTitle>Irrigation input accepted</AlertTitle><AlertDescription>Unsaved route-scoped draft only. No irrigation record exists in FastAPI.</AlertDescription></Alert> : null}</div> : <p className="text-sm text-[var(--text-muted)]">Complete valid inputs to preview the conversion.</p>}</CardContent></Card>
  </div>;
}

function Row({ term, value }: { term: string; value: string }) { return <div><dt className="text-[var(--text-muted)]">{term}</dt><dd className="break-all font-semibold">{value}</dd></div>; }
