/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Route */
        get: operations["health_route_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Info Route */
        get: operations["system_info_route_system_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Farms */
        get: operations["list_farms_farms_get"];
        put?: never;
        /** Create Farm */
        post: operations["create_farm_farms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Farm */
        get: operations["get_farm_farms__farm_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/{farm_id}/plots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plots */
        get: operations["list_plots_farms__farm_id__plots_get"];
        put?: never;
        /** Create Plot */
        post: operations["create_plot_farms__farm_id__plots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plots/{plot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plot */
        get: operations["get_plot_plots__plot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plots/{plot_id}/crop-cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Crop Cycle For Plot */
        post: operations["create_crop_cycle_for_plot_plots__plot_id__crop_cycles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{state_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session State */
        get: operations["get_session_state_sessions__state_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{state_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session History */
        get: operations["get_session_history_sessions__state_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{state_id}/predict-disease": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict Disease */
        post: operations["predict_disease_sessions__state_id__predict_disease_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{state_id}/weather-snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Weather Snapshot Route */
        get: operations["get_weather_snapshot_route_sessions__state_id__weather_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{state_id}/compute-water-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Water State Route */
        post: operations["compute_water_state_route_sessions__state_id__compute_water_state_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{state_id}/update-twin-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Twin State Route */
        post: operations["update_twin_state_route_sessions__state_id__update_twin_state_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{state_id}/advance-one-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance One Day Route */
        post: operations["advance_one_day_route_sessions__state_id__advance_one_day_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{state_id}/simulate-actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate Actions Route */
        post: operations["simulate_actions_route_sessions__state_id__simulate_actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{state_id}/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommend Route */
        post: operations["recommend_route_sessions__state_id__recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{state_id}/narrate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Narrate Route */
        post: operations["narrate_route_sessions__state_id__narrate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{state_id}/actual-actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Actual Actions */
        get: operations["list_actual_actions_sessions__state_id__actual_actions_get"];
        put?: never;
        /** Record Actual Action */
        post: operations["record_actual_action_sessions__state_id__actual_actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionEnum
         * @enum {string}
         */
        ActionEnum: "IRRIGATE_NOW" | "IRRIGATE_IN_6H" | "IRRIGATE_TOMORROW_AM" | "NO_IRRIGATION_24H";
        /** ActualActionCreateRequest */
        ActualActionCreateRequest: {
            action: components["schemas"]["ActionEnum"];
            /**
             * Performed At
             * Format: date-time
             */
            performed_at: string;
            /** Amount Mm */
            amount_mm?: number | null;
            /** Related Recommendation Id */
            related_recommendation_id?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ActualActionResponse */
        ActualActionResponse: {
            /** Actual Action Id */
            actual_action_id: string;
            /** State Id */
            state_id: string;
            /** Related Recommendation Id */
            related_recommendation_id: string | null;
            action: components["schemas"]["ActionEnum"];
            /**
             * Performed At
             * Format: date-time
             */
            performed_at: string;
            /** Amount Mm */
            amount_mm: number | null;
            /** Notes */
            notes: string | null;
            /**
             * Recorded At
             * Format: date-time
             */
            recorded_at: string;
        };
        /** AdvanceOneDayRequest */
        AdvanceOneDayRequest: {
            /** State Id */
            state_id: string;
            /** Advancement Id */
            advancement_id: string;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            weather: components["schemas"]["WeatherInput"];
            last_irrigation_event?: components["schemas"]["LastIrrigationEvent"] | null;
        };
        /** AdvanceOneDayResponse */
        AdvanceOneDayResponse: {
            /** State Id */
            state_id: string;
            /** Advancement Id */
            advancement_id: string;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /** Advancement Created */
            advancement_created: boolean;
            water_state: components["schemas"]["WaterStateResponse"];
            twin_state: components["schemas"]["UpdateTwinStateResponse"];
        };
        /**
         * CautionReason
         * @enum {string}
         */
        CautionReason: "HIGH_UNCERTAINTY" | "FUNGAL_DISEASE_RISK";
        /** ComputeWaterStateRequest */
        ComputeWaterStateRequest: {
            /** State Id */
            state_id: string;
            /** Water Update Id */
            water_update_id?: string | null;
            /**
             * Current Date
             * Format: date
             */
            current_date: string;
            weather: components["schemas"]["WeatherInput"];
            last_irrigation_event?: components["schemas"]["LastIrrigationEvent"] | null;
            /** Observed At */
            observed_at?: string | null;
            /** Base Water Observation Id */
            base_water_observation_id?: string | null;
            /** Base Water Sequence */
            base_water_sequence?: number | null;
        };
        /** CreateCropCycleRequest */
        CreateCropCycleRequest: {
            crop_type: components["schemas"]["CropType"];
            /**
             * Planting Date
             * Format: date
             */
            planting_date: string;
        };
        /**
         * CreateSessionRequest
         * @example {
         *       "crop_type": "tomato",
         *       "location": {
         *         "latitude": 17.385,
         *         "longitude": 78.4867,
         *         "name": "Hyderabad Farm"
         *       },
         *       "planting_date": "2026-07-01",
         *       "soil_texture": "sandy_loam"
         *     }
         */
        CreateSessionRequest: {
            crop_type: components["schemas"]["CropType"];
            /**
             * Planting Date
             * Format: date
             */
            planting_date: string;
            location: components["schemas"]["Location"];
            soil_texture: components["schemas"]["SoilTexture"];
        };
        /**
         * CropType
         * @enum {string}
         */
        CropType: "tomato";
        /**
         * DiseaseCategory
         * @enum {string}
         */
        DiseaseCategory: "fungal" | "bacterial" | "viral" | "none";
        /** DiseasePredictionResponse */
        DiseasePredictionResponse: {
            /** State Id */
            state_id: string;
            crop_type: components["schemas"]["CropType"];
            /** Predicted Label */
            predicted_label: string;
            disease_category: components["schemas"]["DiseaseCategory"];
            /** Class Probs */
            class_probs: {
                [key: string]: number;
            };
            /** Confidence Calibrated */
            confidence_calibrated: number;
            /** Uncertainty Score */
            uncertainty_score: number;
            uncertainty_band: components["schemas"]["UncertaintyBand"];
            /**
             * Predicted At
             * Format: date-time
             */
            predicted_at: string;
        };
        /**
         * EtoMethod
         * @enum {string}
         */
        EtoMethod: "penman_monteith" | "hargreaves_samani";
        /** FarmCreateRequest */
        FarmCreateRequest: {
            /** Name */
            name: string;
        };
        /** FarmResponse */
        FarmResponse: {
            /** Farm Id */
            farm_id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * GrowthStage
         * @enum {string}
         */
        GrowthStage: "initial" | "development" | "mid_season" | "late_season";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /** HistoryEvent */
        HistoryEvent: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            growth_stage: components["schemas"]["GrowthStage"];
            /** Predicted Label */
            predicted_label: string;
            /** Root Zone Depletion */
            root_zone_depletion: number;
            stress_band: components["schemas"]["StressBand"];
        };
        /**
         * IrrigationConstraint
         * @enum {string}
         */
        IrrigationConstraint: "NONE" | "AVOID_OVERHEAD_IRRIGATION" | "PREFER_EARLY_MORNING_WINDOW";
        /**
         * IrrigationEventSource
         * @enum {string}
         */
        IrrigationEventSource: "MANUAL" | "CONVERTED_FROM_LITRES" | "CONVERTED_FROM_DRIP_RUNTIME" | "CONTROLLER" | "SENSOR" | "LEGACY_REQUEST";
        /** LastIrrigationEvent */
        LastIrrigationEvent: {
            /** Irrigation Event Id */
            irrigation_event_id?: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Amount Mm */
            amount_mm: number;
            /** @default LEGACY_REQUEST */
            source: components["schemas"]["IrrigationEventSource"];
        };
        /** Location */
        Location: {
            /** Name */
            name: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Elevation M */
            elevation_m?: number | null;
        };
        /**
         * MoistureState
         * @enum {string}
         */
        MoistureState: "adequate" | "moderate_deficit" | "depleted";
        /** NarrationResponse */
        NarrationResponse: {
            /** State Id */
            state_id: string;
            /** Headline */
            headline: string;
            /** Rationale */
            rationale: string;
            /** Caution */
            caution?: string | null;
        };
        /**
         * ObservationTimeBasis
         * @enum {string}
         */
        ObservationTimeBasis: "EXPLICIT" | "DATE_ONLY_UTC_START" | "SERVER_RECEIVED";
        /** PlotCreateRequest */
        PlotCreateRequest: {
            /** Name */
            name: string;
            location: components["schemas"]["Location"];
            soil_texture: components["schemas"]["SoilTexture"];
        };
        /** PlotResponse */
        PlotResponse: {
            /** Plot Id */
            plot_id: string;
            /** Farm Id */
            farm_id: string;
            /** Name */
            name: string;
            location: components["schemas"]["Location"];
            soil_texture: components["schemas"]["SoilTexture"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PredictDiseaseRequest
         * @example {
         *       "image_base64": "iVBORw0KGgoAAAANSUhEUgAAAAUA",
         *       "model_version": "tomato_disease_v1.2",
         *       "state_id": "state-123"
         *     }
         */
        PredictDiseaseRequest: {
            /** State Id */
            state_id: string;
            /** Image Base64 */
            image_base64: string;
            /** Model Version */
            model_version: string;
        };
        /**
         * RecommendationResponse
         * @example {
         *       "caution_reasons": [
         *         "FUNGAL_DISEASE_RISK"
         *       ],
         *       "chosen_action": "IRRIGATE_TOMORROW_AM",
         *       "decision_reason_codes": [
         *         "DEPLETION_EXCEEDS_RAW",
         *         "FUNGAL_WETNESS_RISK",
         *         "LOW_UNCERTAINTY_CONFIRMS_CONSTRAINT"
         *       ],
         *       "evidence_summary_structured": {
         *         "confidence_calibrated": 0.91,
         *         "disease_category": "fungal",
         *         "predicted_label": "late_blight",
         *         "raw_threshold": 27,
         *         "root_zone_depletion": 31,
         *         "uncertainty_band": "low",
         *         "uncertainty_score": 0.06
         *       },
         *       "inspection_advisory": false,
         *       "irrigation_constraint": "AVOID_OVERHEAD_IRRIGATION",
         *       "recommended_at": "2026-07-05T10:00:00Z",
         *       "state_id": "state-123"
         *     }
         */
        RecommendationResponse: {
            /** Recommendation Id */
            recommendation_id?: string | null;
            /** State Id */
            state_id: string;
            chosen_action: components["schemas"]["ActionEnum"];
            irrigation_constraint: components["schemas"]["IrrigationConstraint"];
            /** Inspection Advisory */
            inspection_advisory: boolean;
            /** Decision Reason Codes */
            decision_reason_codes: string[];
            /** Caution Reasons */
            caution_reasons: components["schemas"]["CautionReason"][];
            /** Evidence Summary Structured */
            evidence_summary_structured: {
                [key: string]: unknown;
            };
            /**
             * Recommended At
             * Format: date-time
             */
            recommended_at: string;
        };
        /** SessionHistoryResponse */
        SessionHistoryResponse: {
            /** State Id */
            state_id: string;
            /** History */
            history: components["schemas"]["HistoryEvent"][];
        };
        /** SessionResponse */
        SessionResponse: {
            /** State Id */
            state_id: string;
            crop_type: components["schemas"]["CropType"];
            /**
             * Planting Date
             * Format: date
             */
            planting_date: string;
            location: components["schemas"]["Location"];
            soil_texture: components["schemas"]["SoilTexture"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SessionStateResponse */
        SessionStateResponse: {
            /** State Id */
            state_id: string;
            crop_type: components["schemas"]["CropType"];
            /**
             * Planting Date
             * Format: date
             */
            planting_date: string;
            location: components["schemas"]["Location"];
            soil_texture: components["schemas"]["SoilTexture"];
            current_state: components["schemas"]["TwinCurrentState"];
        };
        /** SimulateActionsRequest */
        SimulateActionsRequest: {
            /** State Id */
            state_id: string;
            /** Actions */
            actions: components["schemas"]["ActionEnum"][];
        };
        /** SimulateActionsResponse */
        SimulateActionsResponse: {
            /** State Id */
            state_id: string;
            /** Simulations */
            simulations: components["schemas"]["SimulatedActionResult"][];
            /**
             * Simulated At
             * Format: date-time
             */
            simulated_at: string;
        };
        /** SimulatedActionResult */
        SimulatedActionResult: {
            action: components["schemas"]["ActionEnum"];
            /** Projected Root Zone Depletion */
            projected_root_zone_depletion: number;
            /** Projected Raw Crossing */
            projected_raw_crossing: boolean;
            projected_stress_band: components["schemas"]["StressBand"];
            /** Projected Water Use */
            projected_water_use: number;
            /** Disease Wetness Risk Note */
            disease_wetness_risk_note: string;
        };
        /**
         * SoilTexture
         * @enum {string}
         */
        SoilTexture: "sand" | "sandy_loam" | "loam" | "silty_loam" | "clay_loam" | "clay";
        /** StateIdRequest */
        StateIdRequest: {
            /** State Id */
            state_id: string;
        };
        /**
         * StressBand
         * @enum {string}
         */
        StressBand: "low" | "medium" | "high";
        /** TwinCurrentState */
        TwinCurrentState: {
            crop_type: components["schemas"]["CropType"];
            growth_stage: components["schemas"]["GrowthStage"];
            /** Days Since Planting */
            days_since_planting: number;
            /** Predicted Label */
            predicted_label: string;
            disease_category: components["schemas"]["DiseaseCategory"];
            /** Confidence Calibrated */
            confidence_calibrated: number;
            /** Uncertainty Score */
            uncertainty_score: number;
            uncertainty_band: components["schemas"]["UncertaintyBand"];
            /** Eto Computed */
            eto_computed: number;
            eto_method: components["schemas"]["EtoMethod"];
            /** Kc */
            kc: number;
            /** Etc */
            etc: number;
            /** Taw */
            taw: number;
            /** Raw Threshold */
            raw_threshold: number;
            /** Raw Root Zone Depletion Mm */
            raw_root_zone_depletion_mm: number;
            /** Root Zone Depletion Mm */
            root_zone_depletion_mm: number;
            /** Root Zone Depletion */
            root_zone_depletion: number;
            /** Water Surplus Mm */
            water_surplus_mm: number;
            /** Depletion Beyond Taw Mm */
            depletion_beyond_taw_mm: number;
            estimated_moisture_state: components["schemas"]["MoistureState"];
            stress_band: components["schemas"]["StressBand"];
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            observation_time_basis: components["schemas"]["ObservationTimeBasis"];
            /**
             * Last Update Time
             * Format: date-time
             */
            last_update_time: string;
        };
        /**
         * UncertaintyBand
         * @enum {string}
         */
        UncertaintyBand: "low" | "medium" | "high";
        /** UpdateTwinStateResponse */
        UpdateTwinStateResponse: {
            /** State Id */
            state_id: string;
            current_state: components["schemas"]["TwinCurrentState"];
            /** State History Count */
            state_history_count: number;
            /** Snapshot Id */
            snapshot_id?: string | null;
            /**
             * Snapshot Created
             * @default true
             */
            snapshot_created: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WaterStateResponse
         * @example {
         *       "computed_at": "2026-07-05T10:00:00Z",
         *       "crop_type": "tomato",
         *       "depletion_beyond_taw_mm": 0,
         *       "estimated_moisture_state": "moderate_deficit",
         *       "etc": 3.84,
         *       "eto_computed": 4.8,
         *       "eto_delta_pct": -4,
         *       "eto_method": "penman_monteith",
         *       "eto_reference_feed": 5,
         *       "field_capacity_assumed": 0.22,
         *       "growth_stage": "development",
         *       "kc": 0.8,
         *       "observation_time_basis": "DATE_ONLY_UTC_START",
         *       "observed_at": "2026-07-05T00:00:00Z",
         *       "p_allowable": 0.5,
         *       "raw_root_zone_depletion_mm": 18,
         *       "raw_threshold": 24,
         *       "root_depth_assumed": 0.4,
         *       "root_zone_depletion": 18,
         *       "root_zone_depletion_mm": 18,
         *       "soil_texture": "sandy_loam",
         *       "state_id": "state-123",
         *       "stress_band": "medium",
         *       "taw": 48,
         *       "water_surplus_mm": 0,
         *       "wilting_point_assumed": 0.1
         *     }
         */
        WaterStateResponse: {
            /** State Id */
            state_id: string;
            /** Water Observation Id */
            water_observation_id?: string | null;
            /**
             * Water Sequence
             * @default 0
             */
            water_sequence: number;
            /** Base Water Observation Id */
            base_water_observation_id?: string | null;
            /**
             * Base Water Sequence
             * @default 0
             */
            base_water_sequence: number;
            /**
             * Previous Root Zone Depletion Mm
             * @default 0
             */
            previous_root_zone_depletion_mm: number;
            /** Water Update Id */
            water_update_id?: string | null;
            /** Reported Irrigation Event Id */
            reported_irrigation_event_id?: string | null;
            /** Applied Irrigation Event Id */
            applied_irrigation_event_id?: string | null;
            /**
             * Effective Irrigation Mm
             * @default 0
             */
            effective_irrigation_mm: number;
            /**
             * Irrigation Event Already Accounted For
             * @default false
             */
            irrigation_event_already_accounted_for: boolean;
            crop_type: components["schemas"]["CropType"];
            growth_stage: components["schemas"]["GrowthStage"];
            soil_texture: components["schemas"]["SoilTexture"];
            /** Eto Computed */
            eto_computed: number;
            eto_method: components["schemas"]["EtoMethod"];
            /** Eto Reference Feed */
            eto_reference_feed: number | null;
            /** Eto Delta Pct */
            eto_delta_pct: number | null;
            /** Kc */
            kc: number;
            /** Etc */
            etc: number;
            /** Field Capacity Assumed */
            field_capacity_assumed: number;
            /** Wilting Point Assumed */
            wilting_point_assumed: number;
            /** Root Depth Assumed */
            root_depth_assumed: number;
            /** Taw */
            taw: number;
            /** P Allowable */
            p_allowable: number;
            /** Raw Threshold */
            raw_threshold: number;
            /** Raw Root Zone Depletion Mm */
            raw_root_zone_depletion_mm: number;
            /** Root Zone Depletion Mm */
            root_zone_depletion_mm: number;
            /** Root Zone Depletion */
            root_zone_depletion: number;
            /** Water Surplus Mm */
            water_surplus_mm: number;
            /** Depletion Beyond Taw Mm */
            depletion_beyond_taw_mm: number;
            estimated_moisture_state: components["schemas"]["MoistureState"];
            stress_band: components["schemas"]["StressBand"];
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            observation_time_basis: components["schemas"]["ObservationTimeBasis"];
        };
        /** WeatherInput */
        WeatherInput: {
            /** Tmin C */
            tmin_c: number;
            /** Tmax C */
            tmax_c: number;
            /** Humidity Pct */
            humidity_pct: number;
            /** Wind Speed Mps */
            wind_speed_mps: number;
            /** Shortwave Radiation Sum Mj M2 */
            shortwave_radiation_sum_mj_m2?: number | null;
            /** Rainfall Mm */
            rainfall_mm: number;
            /** Eto Reference Feed */
            eto_reference_feed?: number | null;
        };
        /** WeatherSnapshotResponse */
        WeatherSnapshotResponse: {
            /** State Id */
            state_id: string;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /**
             * Source
             * @constant
             */
            source: "open_meteo";
            /** Source Timezone */
            source_timezone: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Tmin C */
            tmin_c: number;
            /** Tmax C */
            tmax_c: number;
            /** Humidity Pct */
            humidity_pct: number;
            /** Wind Speed Mps */
            wind_speed_mps: number;
            /** Wind Source Height M */
            wind_source_height_m: number;
            /** Wind Normalized Height M */
            wind_normalized_height_m: number;
            /** Rainfall Mm */
            rainfall_mm: number;
            /** Shortwave Radiation Sum Mj M2 */
            shortwave_radiation_sum_mj_m2: number;
            /** Eto Reference Feed */
            eto_reference_feed: number;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_route_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    system_info_route_system_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_farms_farms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmResponse"][];
                };
            };
        };
    };
    create_farm_farms_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_farm_farms__farm_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plots_farms__farm_id__plots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlotResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plot_farms__farm_id__plots_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlotCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plot_plots__plot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_crop_cycle_for_plot_plots__plot_id__crop_cycles_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCropCycleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_state_sessions__state_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                state_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_history_sessions__state_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                state_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_disease_sessions__state_id__predict_disease_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                state_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictDiseaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiseasePredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weather_snapshot_route_sessions__state_id__weather_snapshot_get: {
        parameters: {
            query: {
                target_date: string;
            };
            header?: never;
            path: {
                state_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeatherSnapshotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_water_state_route_sessions__state_id__compute_water_state_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                state_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComputeWaterStateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_twin_state_route_sessions__state_id__update_twin_state_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                state_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StateIdRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateTwinStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_one_day_route_sessions__state_id__advance_one_day_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                state_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdvanceOneDayRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvanceOneDayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_actions_route_sessions__state_id__simulate_actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                state_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateActionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulateActionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_route_sessions__state_id__recommend_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                state_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    narrate_route_sessions__state_id__narrate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                state_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NarrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_actual_actions_sessions__state_id__actual_actions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                state_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActualActionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_actual_action_sessions__state_id__actual_actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                state_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualActionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActualActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
