"use client";
import { useEffect, useRef, useState } from "react";
import { FlaskConical, TriangleAlert } from "lucide-react";
import { ApiErrorPanel } from "@/components/shared-states/api-error-panel";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { actions, type Action } from "@/lib/api/contracts";
import { useSimulateActions } from "@/lib/api/hooks/use-decisions";
import { queryKeys } from "@/lib/api/query-keys";
import { useQueryClient } from "@tanstack/react-query";
import { canonicalJson } from "../identity";
import { actionLabels } from "../decision-labels";
import type { AcceptedSimulationResult } from "../workflow-results";

export function simulationSourceSignature(twinSourceSignature: string, selected: Action[]) { return canonicalJson({ twin_source_signature: twinSourceSignature, ordered_candidates: selected }); }

export function SimulationStage({ stateId, twinSourceSignature, retained, current, onAccepted, onSuperseded }: { stateId: string; twinSourceSignature: string; retained?: AcceptedSimulationResult; current?: AcceptedSimulationResult; onAccepted: (value: AcceptedSimulationResult) => void; onSuperseded: () => void }) {
  const client = useQueryClient(); const mutation = useSimulateActions(); const [selected, setSelected] = useState<Action[]>(() => retained?.response.simulations.map((item) => item.action) ?? [...actions]); const [error, setError] = useState<unknown>(); const generation = useRef(0); const controller = useRef<AbortController | undefined>(undefined); const sourceRef = useRef(twinSourceSignature);
  useEffect(() => { if (sourceRef.current !== twinSourceSignature) { controller.current?.abort(); generation.current += 1; sourceRef.current = twinSourceSignature; onSuperseded(); } }, [onSuperseded, twinSourceSignature]);
  useEffect(() => () => { controller.current?.abort(); generation.current += 1; }, []);
  function toggle(action: Action) { const next = selected.includes(action) ? selected.filter((value) => value !== action) : actions.filter((value) => value === action || selected.includes(value)); setSelected(next); setError(undefined); onSuperseded(); }
  async function submit() { if (!selected.length) { setError(new Error("Select at least one candidate action.")); return; } if (mutation.isPending) return; const sourceSignature = simulationSourceSignature(twinSourceSignature, selected); const request = ++generation.current; const capturedSource = twinSourceSignature; const abort = new AbortController(); controller.current = abort; setError(undefined); try { const response = await mutation.mutateAsync({ stateId, input: { state_id: stateId, actions: selected }, signal: abort.signal }); if (generation.current !== request || sourceRef.current !== capturedSource) return; const accepted = { response, sourceSignature, twinSourceSignature: capturedSource } satisfies AcceptedSimulationResult; client.setQueryData(queryKeys.simulation(stateId), response); onAccepted(accepted); } catch (cause) { if (!abort.signal.aborted && generation.current === request) setError(cause); } finally { if (controller.current === abort) controller.current = undefined; } }
  const shown = current ?? retained;
  return <div className="grid gap-5 xl:grid-cols-[minmax(18rem,.65fr)_minmax(0,1.35fr)]"><Card><CardHeader><CardTitle>Deterministic scenario comparison</CardTitle><CardDescription>Select candidate inputs for FastAPI to project. These are not recommended choices.</CardDescription></CardHeader><CardContent className="grid gap-4"><fieldset className="grid gap-2"><legend className="mb-2 text-sm font-semibold">Candidate actions</legend>{actions.map((action) => <label key={action} className="flex items-center gap-3 rounded-lg border border-[var(--border-subtle)] p-3 text-sm"><input type="checkbox" checked={selected.includes(action)} onChange={() => toggle(action)} /> <span><span className="block font-semibold">{actionLabels[action]}</span><code className="text-xs text-[var(--text-muted)]">{action}</code></span></label>)}</fieldset>{selected.length === 0 ? <p role="alert" className="text-sm text-[var(--state-destructive-strong)]">Select at least one candidate.</p> : null}<Button type="button" onClick={() => void submit()} disabled={!selected.length || mutation.isPending} aria-busy={mutation.isPending}><FlaskConical className="size-4" />{mutation.isPending ? "Simulating candidates…" : "Simulate selected candidates"}</Button>{error ? <ApiErrorPanel error={error} title="Simulation unavailable" /> : null}</CardContent></Card><div className="grid content-start gap-3">{shown && !current ? <Alert variant="warning"><TriangleAlert className="size-5" /><AlertTitle>Previous simulation superseded</AlertTitle><AlertDescription>Its canonical twin or selected candidates changed. Run the explicit comparison to continue.</AlertDescription></Alert> : null}{shown ? shown.response.simulations.map((item, index) => <Card key={`${item.action}-${index}`}><CardHeader><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle className="text-lg">{actionLabels[item.action]}</CardTitle><Badge variant={item.projected_stress_band === "high" ? "warning" : "neutral"}>{item.projected_stress_band} stress</Badge></div><CardDescription><code>{item.action}</code> · candidate {index + 1} in request order</CardDescription></CardHeader><CardContent><dl className="grid gap-3 text-sm sm:grid-cols-2"><Metric label="Projected depletion" value={`${item.projected_root_zone_depletion.toFixed(2)} mm`} /><Metric label="RAW crossing" value={item.projected_raw_crossing ? "Yes" : "No"} /><Metric label="Projected water use" value={`${item.projected_water_use.toFixed(2)} mm`} /><Metric label="Wetness-risk note" value={item.disease_wetness_risk_note || "None returned"} /></dl></CardContent></Card>) : <Alert variant="neutral"><FlaskConical className="size-5" /><AlertTitle>No scenario comparison yet</AlertTitle><AlertDescription>FastAPI will return every selected candidate in request order.</AlertDescription></Alert>}</div></div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div><dt className="text-[var(--text-muted)]">{label}</dt><dd className="font-semibold">{value}</dd></div>; }
