"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { Sparkles, TriangleAlert } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { ApiErrorPanel } from "@/components/shared-states/api-error-panel";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useRecommend } from "@/lib/api/hooks/use-decisions";
import { queryKeys } from "@/lib/api/query-keys";
import { actionLabels, readableCode } from "../decision-labels";
import type { AcceptedRecommendationResult } from "../workflow-results";

export function RecommendationStage({ stateId, sourceSignature, retained, current, onAccepted }: { stateId: string; sourceSignature: string; retained?: AcceptedRecommendationResult; current?: AcceptedRecommendationResult; onAccepted: (value: AcceptedRecommendationResult) => void }) {
  const client = useQueryClient(); const mutation = useRecommend(); const [error, setError] = useState<unknown>(); const generation = useRef(0); const controller = useRef<AbortController | undefined>(undefined); const sourceRef = useRef(sourceSignature);
  useEffect(() => { if (sourceRef.current !== sourceSignature) { controller.current?.abort(); generation.current += 1; sourceRef.current = sourceSignature; } }, [sourceSignature]);
  useEffect(() => () => { controller.current?.abort(); generation.current += 1; }, []);
  async function submit() { if (mutation.isPending) return; const request = ++generation.current; const captured = sourceSignature; const abort = new AbortController(); controller.current = abort; setError(undefined); try { const response = await mutation.mutateAsync({ stateId, signal: abort.signal }); if (request !== generation.current || sourceRef.current !== captured) return; client.setQueryData(queryKeys.recommendation(stateId), response); onAccepted({ response, sourceSignature: captured }); } catch (cause) { if (!abort.signal.aborted && request === generation.current) setError(cause); } finally { if (controller.current === abort) controller.current = undefined; } }
  const shown = current ?? retained; const result = shown?.response;
  return <div className="grid gap-5 xl:grid-cols-[minmax(18rem,.65fr)_minmax(0,1.35fr)]"><Card><CardHeader><CardTitle>Deterministic FastAPI recommendation</CardTitle><CardDescription>The backend owns action selection. Disease evidence can constrain irrigation method or inspection needs; it does not independently decide irrigation.</CardDescription></CardHeader><CardContent className="grid gap-4"><Button type="button" onClick={() => void submit()} disabled={mutation.isPending} aria-busy={mutation.isPending}><Sparkles className="size-4" />{mutation.isPending ? "Requesting recommendation…" : "Request recommendation"}</Button>{error ? <ApiErrorPanel error={error} title="Recommendation unavailable" /> : null}</CardContent></Card><div>{shown && !current ? <Alert variant="warning" className="mb-4"><TriangleAlert className="size-5" /><AlertTitle>Previous recommendation superseded</AlertTitle><AlertDescription>The simulation source changed. Request a new FastAPI recommendation.</AlertDescription></Alert> : null}{result ? <Card><CardHeader><div className="flex flex-wrap gap-2"><Badge variant="success">Backend selected</Badge>{result.caution_reasons.map((reason) => <Badge key={reason} variant="warning">{readableCode(reason)}</Badge>)}</div><CardTitle>{actionLabels[result.chosen_action]}</CardTitle><CardDescription>Recommended {new Date(result.recommended_at).toLocaleString()}</CardDescription></CardHeader><CardContent className="grid gap-4"><dl className="grid gap-3 text-sm sm:grid-cols-2"><Metric label="Irrigation constraint" value={readableCode(result.irrigation_constraint)} /><Metric label="Inspection advisory" value={result.inspection_advisory ? "Required" : "Not required"} /></dl><div><h4 className="text-sm font-semibold">Decision reasons</h4><ul className="mt-2 grid gap-1 text-sm">{result.decision_reason_codes.map((code) => <li key={code}>{readableCode(code)} <code className="text-xs text-[var(--text-muted)]">({code})</code></li>)}</ul></div><details><summary className="cursor-pointer text-sm font-semibold">Structured evidence summary</summary><pre className="mt-2 overflow-x-auto rounded-lg bg-[var(--surface-sunken)] p-3 text-xs">{JSON.stringify(result.evidence_summary_structured, null, 2)}</pre></details><Link href={`/actions/${encodeURIComponent(stateId)}?action=${result.chosen_action}${result.recommendation_id ? `&recommendationId=${encodeURIComponent(result.recommendation_id)}` : ""}`} className="font-semibold text-[var(--agronomy-strong)] underline">Record actual action</Link></CardContent></Card> : <Alert variant="neutral"><Sparkles className="size-5" /><AlertTitle>No recommendation yet</AlertTitle><AlertDescription>Request it explicitly after the current simulation.</AlertDescription></Alert>}</div></div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div><dt className="text-[var(--text-muted)]">{label}</dt><dd className="font-semibold">{value}</dd></div>; }
