import { createCropCycle, createFarm, createPlot, createSession, getSession } from '@/lib/api/operations';

const response = (body: unknown) => ({ ok: true, status: 200, text: async () => JSON.stringify(body) }) as Response;
afterEach(() => jest.restoreAllMocks());

describe('Milestone 2 API requests', () => {
  it('sends exact farm creation payload once', async () => { globalThis.fetch = jest.fn().mockResolvedValue(response({ farm_id: 'f', name: 'Farm', created_at: 'now', updated_at: 'now' })); await createFarm({ name: 'Farm' }); expect(globalThis.fetch).toHaveBeenCalledTimes(1); expect(JSON.parse((globalThis.fetch as jest.Mock).mock.calls[0][1].body)).toEqual({ name: 'Farm' }); });
  it('sends nested plot payload to the encoded farm route', async () => { globalThis.fetch = jest.fn().mockResolvedValue(response({ plot_id: 'p', farm_id: 'farm/a', name: 'P', location: { name: 'L', latitude: 0, longitude: 0 }, soil_texture: 'loam', created_at: 'now', updated_at: 'now' })); await createPlot('farm/a', { name: 'P', location: { name: 'L', latitude: 0, longitude: 0 }, soil_texture: 'loam' }); expect((globalThis.fetch as jest.Mock).mock.calls[0][0]).toContain('/farms/farm%2Fa/plots'); });
  it('sends exact standalone session body', async () => { globalThis.fetch = jest.fn().mockResolvedValue(response({ state_id: 's', crop_type: 'tomato', planting_date: '2026-08-13', location: { name: 'L', latitude: 0, longitude: 0 }, soil_texture: 'loam', created_at: 'now' })); const body = { crop_type: 'tomato' as const, planting_date: '2026-08-13', location: { name: 'L', latitude: 0, longitude: 0 }, soil_texture: 'loam' as const }; await createSession(body); expect(JSON.parse((globalThis.fetch as jest.Mock).mock.calls[0][1].body)).toEqual(body); });
  it('sends only crop and date for a plot crop cycle', async () => { globalThis.fetch = jest.fn().mockResolvedValue(response({ state_id: 's', crop_type: 'tomato', planting_date: '2026-08-13', location: { name: 'L', latitude: 0, longitude: 0 }, soil_texture: 'loam', created_at: 'now' })); await createCropCycle('plot/a', { crop_type: 'tomato', planting_date: '2026-08-13' }); expect((globalThis.fetch as jest.Mock).mock.calls[0][0]).toContain('/plots/plot%2Fa/crop-cycles'); expect(JSON.parse((globalThis.fetch as jest.Mock).mock.calls[0][1].body)).toEqual({ crop_type: 'tomato', planting_date: '2026-08-13' }); });
  it('encodes trimmed state IDs', async () => { globalThis.fetch = jest.fn().mockResolvedValue(response({ state_id: 'state/a', crop_type: 'tomato', planting_date: '2026-08-13', location: { name: 'L', latitude: 0, longitude: 0 }, soil_texture: 'loam', current_state: { crop_type: 'tomato' } })); await expect(getSession(' state/a ')).rejects.toMatchObject({ kind: 'malformed' }); expect((globalThis.fetch as jest.Mock).mock.calls[0][0]).toContain('/sessions/state%2Fa'); });
});
