import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react-native';
import type { PropsWithChildren } from 'react';
import { DiseaseWorkflow } from '@/features/workflow/disease';
import { IrrigationWorkflow } from '@/features/workflow/irrigation';
import { WeatherWorkflow } from '@/features/workflow/weather';
import { queryKeys } from '@/lib/api';

const mockLibraryPermission = jest.fn(); const mockLibrary = jest.fn(); const mockCameraPermission = jest.fn(); const mockCamera = jest.fn();
jest.mock('expo-image-picker', () => ({ requestMediaLibraryPermissionsAsync: (...args: unknown[]) => mockLibraryPermission(...args), launchImageLibraryAsync: (...args: unknown[]) => mockLibrary(...args), requestCameraPermissionsAsync: (...args: unknown[]) => mockCameraPermission(...args), launchCameraAsync: (...args: unknown[]) => mockCamera(...args) }));

const originalFetch = globalThis.fetch;
const clients: QueryClient[] = [];
function setup() { const client = new QueryClient({ defaultOptions: { queries: { retry: false, gcTime: Infinity }, mutations: { retry: false, gcTime: Infinity } } }); clients.push(client); client.setQueryData(queryKeys.systemInfo(), { disease_model: { model_version: 'authoritative-model' } }); const wrapper = ({ children }: PropsWithChildren) => <QueryClientProvider client={client}>{children}</QueryClientProvider>; return { wrapper }; }
beforeEach(() => { mockLibraryPermission.mockReset(); mockLibrary.mockReset(); mockCameraPermission.mockReset(); mockCamera.mockReset(); });
afterEach(() => { clients.splice(0).forEach((client) => client.clear()); globalThis.fetch = originalFetch; jest.restoreAllMocks(); });

describe('Milestone 3 disease phone states', () => {
  it('shows an empty image state', async () => { const { wrapper } = setup(); await render(<DiseaseWorkflow stateId="state-a" />, { wrapper }); expect(screen.getByText('No leaf image selected')).toBeOnTheScreen(); });
  it('treats library cancellation as a non-error', async () => { const { wrapper } = setup(); mockLibraryPermission.mockResolvedValue({ granted: true }); mockLibrary.mockResolvedValue({ canceled: true, assets: null }); await render(<DiseaseWorkflow stateId="state-a" />, { wrapper }); await act(async () => fireEvent.press(screen.getByLabelText('Choose leaf image'))); expect(mockLibrary).toHaveBeenCalled(); expect(screen.queryByText('Image unavailable')).toBeNull(); });
  it('shows actionable permission denial', async () => { const { wrapper } = setup(); mockCameraPermission.mockResolvedValue({ granted: false }); await render(<DiseaseWorkflow stateId="state-a" />, { wrapper }); await act(async () => fireEvent.press(screen.getByLabelText('Take leaf photo'))); expect(screen.getByText(/Camera access was denied/)).toBeOnTheScreen(); });
  it('renders a constrained selected-image preview and can remove it', async () => { const { wrapper } = setup(); mockLibraryPermission.mockResolvedValue({ granted: true }); mockLibrary.mockResolvedValue({ canceled: false, assets: [{ uri: 'file://leaf.jpg', width: 400, height: 300, base64: 'aGVsbG8=' }] }); await render(<DiseaseWorkflow stateId="state-a" />, { wrapper }); await act(async () => fireEvent.press(screen.getByLabelText('Choose leaf image'))); expect(screen.getByLabelText('Selected tomato leaf preview')).toBeOnTheScreen(); fireEvent.press(screen.getByText('Remove image')); await waitFor(() => expect(screen.getByText('No leaf image selected')).toBeOnTheScreen()); });
  it('submits the system-info model version and renders only returned evidence', async () => { const { wrapper } = setup(); mockLibraryPermission.mockResolvedValue({ granted: true }); mockLibrary.mockResolvedValue({ canceled: false, assets: [{ uri: 'file://leaf.jpg', width: 20, height: 10, base64: 'aGVsbG8=' }] }); globalThis.fetch = jest.fn().mockResolvedValue({ ok: true, status: 200, text: async () => JSON.stringify({ state_id: 'state-a', crop_type: 'tomato', predicted_label: 'Tomato___healthy', disease_category: 'none', class_probs: { Tomato___healthy: 1 }, confidence_calibrated: 1, uncertainty_score: 0, uncertainty_band: 'low', predicted_at: '2026-08-17T10:00:00Z' }) } as Response); await render(<DiseaseWorkflow stateId="state-a" />, { wrapper }); await act(async () => fireEvent.press(screen.getByLabelText('Choose leaf image'))); fireEvent.press(screen.getByText('Run disease prediction')); await waitFor(() => expect(screen.getAllByText('healthy')).toHaveLength(2)); const body = JSON.parse((globalThis.fetch as jest.Mock).mock.calls[0][1].body); expect(body).toEqual({ state_id: 'state-a', image_base64: 'aGVsbG8=', model_version: 'authoritative-model' }); });
  it('shows weather validation instead of filling required blanks', async () => { const { wrapper } = setup(); await render(<WeatherWorkflow stateId="state-a" />, { wrapper }); fireEvent.press(screen.getByText('Accept reviewed weather')); await waitFor(() => expect(screen.getByText('Minimum temperature is required.')).toBeOnTheScreen()); });
  it('reviews no irrigation as an unsaved local choice', async () => { const { wrapper } = setup(); await render(<IrrigationWorkflow stateId="state-a" />, { wrapper }); fireEvent.press(screen.getByText('Accept irrigation input')); await waitFor(() => expect(screen.getByText('Reviewed irrigation draft')).toBeOnTheScreen()); expect(screen.getByText(/No irrigation record or deterministic water state exists yet/)).toBeOnTheScreen(); });
});
