import { advanceOneDay, computeWaterState, updateTwinState } from '@/lib/api';
import { advancement, twinState, waterState } from '../test-support/milestone4-fixtures';

const originalFetch = globalThis.fetch;
const response = (value: unknown) => ({ ok: true, status: 200, text: async () => JSON.stringify(value) } as Response);
afterEach(() => { globalThis.fetch = originalFetch; jest.restoreAllMocks(); });

describe('Milestone 4 exact API operations', () => {
  it('posts the exact deterministic water request and authoritative state identity', async () => { globalThis.fetch = jest.fn().mockResolvedValue(response(waterState)); const input = { state_id: 'state-a', water_update_id: 'water-update-1', current_date: '2026-08-18', weather: { tmin_c: 20, tmax_c: 30, humidity_pct: 60, wind_speed_mps: 2, rainfall_mm: 0 }, last_irrigation_event: null }; await computeWaterState('state-a', input); const [url, init] = (globalThis.fetch as jest.Mock).mock.calls[0]; expect(url).toContain('/sessions/state-a/compute-water-state'); expect(init.method).toBe('POST'); expect(JSON.parse(init.body)).toEqual(input); });
  it('rejects route/body state mismatch before the network', async () => { globalThis.fetch = jest.fn(); await expect(computeWaterState('state-b', { state_id: 'state-a', current_date: '2026-08-18', weather: { tmin_c: 20, tmax_c: 30, humidity_pct: 60, wind_speed_mps: 2, rainfall_mm: 0 } })).rejects.toMatchObject({ code: 'REQUEST_STATE_ID_MISMATCH' }); expect(globalThis.fetch).not.toHaveBeenCalled(); });
  it('posts only state_id for canonical twin update and accepts reuse', async () => { globalThis.fetch = jest.fn().mockResolvedValue(response({ ...twinState, snapshot_created: false })); const result = await updateTwinState('state-a'); expect(result.snapshot_created).toBe(false); const [url, init] = (globalThis.fetch as jest.Mock).mock.calls[0]; expect(url).toContain('/sessions/state-a/update-twin-state'); expect(JSON.parse(init.body)).toEqual({ state_id: 'state-a' }); });
  it('posts one exact advancement and validates nested identities', async () => { globalThis.fetch = jest.fn().mockResolvedValue(response(advancement)); const input = { state_id: 'state-a', advancement_id: 'advance-1', target_date: '2026-08-19', weather: { tmin_c: 20, tmax_c: 30, humidity_pct: 60, wind_speed_mps: 2, rainfall_mm: 0 }, last_irrigation_event: null }; await advanceOneDay('state-a', input); const [url, init] = (globalThis.fetch as jest.Mock).mock.calls[0]; expect(url).toContain('/sessions/state-a/advance-one-day'); expect(JSON.parse(init.body)).toEqual(input); expect((globalThis.fetch as jest.Mock).mock.calls).toHaveLength(1); });
  it('can retry an advancement with the byte-for-byte same request identity and no extra orchestration calls', async () => { globalThis.fetch = jest.fn().mockResolvedValueOnce(response(advancement)).mockResolvedValueOnce(response({ ...advancement, advancement_created: false })); const input = { state_id: 'state-a', advancement_id: 'advance-1', target_date: '2026-08-19', weather: { tmin_c: 20, tmax_c: 30, humidity_pct: 60, wind_speed_mps: 2, rainfall_mm: 0 }, last_irrigation_event: null }; await advanceOneDay('state-a', input); await advanceOneDay('state-a', input); const calls = (globalThis.fetch as jest.Mock).mock.calls; expect(JSON.parse(calls[1][1].body)).toEqual(JSON.parse(calls[0][1].body)); expect(calls.every(([url]) => String(url).includes('advance-one-day'))).toBe(true); });
  it('never invokes future-operation endpoints', async () => { globalThis.fetch = jest.fn().mockResolvedValue(response({ ...twinState, snapshot_created: false })); await updateTwinState('state-a'); const urls = (globalThis.fetch as jest.Mock).mock.calls.map(([url]) => String(url)).join(' '); expect(urls).not.toMatch(/simulate-actions|recommend|narrate|history|actual-actions/); });
});
