import { describe, expect, it } from "vitest";
import type { WeatherSnapshot } from "@/lib/api/contracts";
import { acceptedWeatherFromDraft, emptyWeatherValues, parseWeatherValues, valuesFromSnapshot, weatherOverrideFlags, type WeatherDraft } from "./weather-draft";

const snapshot: WeatherSnapshot = { state_id: "state-1", target_date: "2026-08-04", source: "open_meteo", source_timezone: "Asia/Kolkata", latitude: 17, longitude: 78, tmin_c: 20, tmax_c: 30, humidity_pct: 60, wind_speed_mps: 2, wind_source_height_m: 10, wind_normalized_height_m: 2, rainfall_mm: 0, shortwave_radiation_sum_mj_m2: 18, eto_reference_feed: 4, fetched_at: "2026-08-04T04:00:00Z" };

describe("weather review boundaries", () => {
  it("maps snapshot fields into a review draft and preserves zero", () => { const values = valuesFromSnapshot(snapshot); expect(values.rainfall_mm).toBe("0"); expect(parseWeatherValues(values).rainfall_mm).toBe(0); });
  it.each(["tmin_c", "tmax_c", "humidity_pct", "wind_speed_mps", "rainfall_mm"] as const)("rejects blank required %s", (field) => expect(() => parseWeatherValues({ ...valuesFromSnapshot(snapshot), [field]: "" })).toThrow(/required/));
  it("turns optional blanks into null", () => expect(parseWeatherValues({ ...valuesFromSnapshot(snapshot), shortwave_radiation_sum_mj_m2: "", eto_reference_feed: "" })).toMatchObject({ shortwave_radiation_sum_mj_m2: null, eto_reference_feed: null }));
  it.each([[-1, false], [0, true], [100, true], [101, false]])("enforces humidity %s", (humidity, valid) => { const run = () => parseWeatherValues({ ...valuesFromSnapshot(snapshot), humidity_pct: String(humidity) }); if (valid) expect(run()).toBeTruthy(); else expect(run).toThrow(); });
  it.each([["wind_speed_mps", "-1"], ["shortwave_radiation_sum_mj_m2", "-1"], ["rainfall_mm", "-1"]] as const)("rejects negative %s", (field, value) => expect(() => parseWeatherValues({ ...valuesFromSnapshot(snapshot), [field]: value })).toThrow());
  it("identifies fetched overrides without rewriting values", () => { const weather = parseWeatherValues({ ...valuesFromSnapshot(snapshot), rainfall_mm: "2" }); expect(weatherOverrideFlags(weather, snapshot).rainfall_mm).toBe(true); expect(weather.rainfall_mm).toBe(2); });
  it("keeps manual provenance distinct and acceptance explicit", () => { const draft: WeatherDraft = { targetDate: snapshot.target_date, provenance: "manual", values: valuesFromSnapshot(snapshot) }; const accepted = acceptedWeatherFromDraft("state-1", draft); expect(accepted.provenance).toBe("manual"); expect(accepted.fetchedIdentity).toBeUndefined(); });
  it("changes the acceptance signature when date or values change", () => { const draft: WeatherDraft = { targetDate: snapshot.target_date, provenance: "fetched_reviewed", values: valuesFromSnapshot(snapshot), fetchedIdentity: { stateId: snapshot.state_id, targetDate: snapshot.target_date, fetchedAt: snapshot.fetched_at } }; const first = acceptedWeatherFromDraft("state-1", draft, snapshot); expect(acceptedWeatherFromDraft("state-1", { ...draft, targetDate: "2026-08-05" }, snapshot).signature).not.toBe(first.signature); expect(acceptedWeatherFromDraft("state-1", { ...draft, values: { ...draft.values, rainfall_mm: "3" } }, snapshot).signature).not.toBe(first.signature); });
  it("does not describe a snapshot from another date as current", () => { const draft: WeatherDraft = { targetDate: "2026-08-05", provenance: "manual", values: { ...emptyWeatherValues, ...valuesFromSnapshot(snapshot) } }; expect(acceptedWeatherFromDraft("state-1", draft, snapshot).provenance).toBe("manual"); });
});
